sharkdp/numbat

- README.md
- book/src/cli-installation.md
I found an [AUR package](https://aur.archlinux.org/packages/numbat-bin), and added that to https://numbat.dev/doc/cli-installation.html#installation
Also added installation instructions to the README.
> AUR package

- assets/numbat.sublime-syntax
- assets/numbat.vim
- book/numbat.js
- book/src/list-functions.md
- book/src/procedures.md
- examples/binomial_coefficient.nbt
- examples/booleans.nbt
- examples/prelude_tests.nbt
- numbat/modules/core/booleans.nbt
- numbat/modules/core/strings.nbt
- numbat/modules/prelude.nbt
- numbat/src/ast.rs
- numbat/src/diagnostic.rs
- numbat/src/ffi.rs
- numbat/src/interpreter.rs
- numbat/src/parser.rs
- numbat/src/tokenizer.rs
- numbat/src/typechecker.rs
- numbat/src/typed_ast.rs
- numbat/src/value.rs
- numbat/src/vm.rs
- vscode-extension/syntaxes/numbat.tmLanguage.json
> Add support for arbitrary types in function parameters

- book/src/list-functions.md
Both functions are useful functions, and should be documented so that they are easier to discover
> Document unit_of and value_of functions

- book/src/list-units.md
- numbat/modules/prelude.nbt
- numbat/modules/units/humorous.nbt
From: https://en.wikipedia.org/wiki/Smoot
> Add smoot unit

- numbat-cli/src/main.rs
> Add intro banner and -q/--quiet option to suppress it.

- numbat/src/interpreter.rs
- numbat/src/typechecker.rs
- numbat/src/vm.rs
… instead of returning false
closes #230
> Raise error when comparing base units

- Cargo.lock
- book/src/list-units.md
- numbat-cli/src/completer.rs
- numbat-cli/src/main.rs
- numbat/Cargo.toml
- numbat/examples/inspect.rs
- numbat/src/bytecode_interpreter.rs
- numbat/src/keywords.rs
- numbat/src/lib.rs
- numbat/src/module_importer.rs
- numbat/src/resolver.rs
- numbat/src/unit_registry.rs
> Tab-complete prefixes and module paths

- numbat-cli/src/completer.rs
- numbat-wasm/src/lib.rs
- numbat/src/lib.rs
> Don't autocomplete opening paren after function call that follows `//`

- numbat/modules/core/dimensions.nbt
https://en.wikipedia.org/wiki/Thermal_transmittance
> Added the ThermalTransmittance dimension

- numbat/src/parser.rs
- numbat/src/tokenizer.rs
> Support subscript characters in identifiers

- book/src/list-units.md
- numbat/modules/units/si.nbt
> Add U+2126 OHM SIGN as a short alias for the `ohm` unit

- numbat-wasm/www/index.html
- numbat-wasm/www/main.css
> refactor: remove div's deprecated align attribute

- numbat/src/bytecode_interpreter.rs
> refactor: remove unnecessary borrows

- numbat-cli/src/completer.rs
- numbat/src/module_importer.rs
- numbat/src/number.rs
> refactor: replace strings with single characters

- book/src/date-and-time.md
- numbat/modules/datetime/functions.nbt
Add two new functions for working with dates, without having to care about times.
> Add `date` and `today`

- numbat-cli/src/config.rs
- numbat-cli/src/main.rs
> Add '-i' option to enter interactive session after executing script or expression

- book/src/SUMMARY.md
- book/src/dimension-definitions.md
- book/src/unit-definitions.md
> Improve documentation around ad-hoc units

- book/src/list-units.md
- examples/consistency_others.nbt
- numbat/modules/units/imperial.nbt
> Add imperial volume units

- numbat/src/typechecker.rs
> Fix callables in binary operators

- book/src/list-units.md
- numbat/modules/units/partsperx.nbt
- numbat/src/tokenizer.rs
Add permille unit (and its spelling variations).
> Add permille unit

- numbat-wasm/www/index.html
- numbat-wasm/www/index.js
- numbat-wasm/www/main.css
> fix: layout shifting after terminal loads

- numbat/src/ast.rs
- numbat/src/bytecode_interpreter.rs
- numbat/src/diagnostic.rs
- numbat/src/parser.rs
- numbat/src/prefix_transformer.rs
- numbat/src/tokenizer.rs
- numbat/src/traversal.rs
- numbat/src/typechecker/const_evaluation.rs
- numbat/src/typechecker/error.rs
- numbat/src/typechecker/mod.rs
- numbat/src/typechecker/qualified_type.rs
- numbat/src/typechecker/substitutions.rs
- numbat/src/typechecker/tests/type_inference.rs
- numbat/src/typechecker/type_scheme.rs
- numbat/src/typed_ast.rs
> Add typed holes

- numbat/src/bytecode_interpreter.rs
- numbat/src/traversal.rs
- numbat/src/typechecker/constraints.rs
- numbat/src/typechecker/mod.rs
- numbat/src/typechecker/substitutions.rs
- numbat/src/typechecker/tests/type_checking.rs
- numbat/src/typed_ast.rs
> HasField constraints

- numbat/src/parser.rs
> Better error message for empty string interpolations

- examples/list_tests.nbt
- numbat/modules/core/functions.nbt
- numbat/modules/core/lists.nbt
```
fn negate(x) = -x
assert_eq(sort_by_key(negate, [1, 2, 3]), [3, 2, 1])
assert_eq(sort_by_key(str_length, ["aa", "", "aaaa", "aaa"]), ["", "aa", "aaa", "aaaa"])
```
> Add sort_by_key

- numbat/src/parser.rs
- numbat/src/pretty_print.rs
- numbat/src/tokenizer.rs
- numbat/src/typed_ast.rs
> Support string escape sequences

- numbat/src/bytecode_interpreter.rs
- numbat/src/diagnostic.rs
- numbat/src/ffi/mod.rs
- numbat/src/ffi/procedures.rs
- numbat/src/interpreter.rs
- numbat/src/vm.rs
> Add source spans for assertion error messages

- numbat-cli/tests/integration.rs
- numbat/src/bytecode_interpreter.rs
- numbat/src/lib.rs
- numbat/src/traversal.rs
- numbat/src/typechecker/mod.rs
- numbat/src/typechecker/substitutions.rs
- numbat/src/typechecker/tests/mod.rs
- numbat/src/typed_ast.rs
- numbat/tests/interpreter.rs
> Readable types

- book/src/conversion-functions.md
- book/src/list-functions-strings.md
- examples/tests/strings.nbt
- numbat/modules/core/strings.nbt
- numbat/src/ffi/functions.rs
- numbat/src/ffi/strings.rs
The opposite of `chr`:
```
>>> "❤" -> ord -> hex
0x2764
```
> Add ord(…) function

- numbat/src/bytecode_interpreter.rs
- numbat/src/interpreter/mod.rs
- numbat/src/typechecker/mod.rs
- numbat/src/typechecker/type_scheme.rs
- numbat/src/typed_ast.rs
- numbat/tests/interpreter.rs
> Fix pretty printing for some generic types

- .gitignore
- numbat/examples/inspect.rs
- numbat/src/ffi/datetime.rs
- numbat/src/ffi/functions.rs
- numbat/src/name_resolution.rs
- numbat/src/pretty_print.rs
- numbat/src/typechecker/constraints.rs
- numbat/src/typechecker/map_stack.rs
- numbat/src/typechecker/mod.rs
Fixed clippy warnings and a typo
> Misc cleanup

- book/src/list-units.md
- numbat/modules/units/currency.nbt
- numbat/src/lib.rs
Missed in https://github.com/sharkdp/numbat/pull/571
> Add lowercase alias for EUR

- numbat/src/parser.rs
Added heuristic to check whether user might have been trying to define a function
Before:
```
1 │ f(x,y) = x+y
│        ^ Trailing '=' sign. Use `let ) = …` if you intended to define a new constant.
```
After:
```
1 │ f(x,y) = x+y
│        ^ Trailing '=' sign. Use `fn f(x,y) = …` if you intended to define a function.
```
When defining a variable, the old message is left basically the same except that all identifiers left of the equals sign, not just the last, are part of the error message.
> Improved error message when encountering a trailing equals

- numbat/examples/inspect.rs
- numbat/src/ffi/datetime.rs
- numbat/src/ffi/functions.rs
- numbat/src/ffi/lists.rs
- numbat/src/ffi/lookup.rs
- numbat/src/ffi/mod.rs
- numbat/src/ffi/plot.rs
- numbat/src/ffi/procedures.rs
- numbat/src/ffi/strings.rs
- numbat/src/interpreter/mod.rs
- numbat/src/list.rs
> Boxed some `RuntimeError`s

- numbat-cli/src/main.rs
> Fix colors on Windows

- numbat/src/markup.rs
This is something I wanted to help make a custom formatter a bit easier to write.
> Derive Display for CompactStrCow

- numbat-cli/src/main.rs
> refactor: remove reference and pass by value

- numbat/src/lib.rs
Add both opening and closing parens for functions with arity of zero.
closes https://github.com/sharkdp/numbat/issues/703
> Function parens completions

- book/src/list-units.md
- numbat/modules/core/dimensions.nbt
- numbat/modules/units/si.nbt
ref: https://en.wikipedia.org/wiki/Candela_per_square_metre
resolve #709
> feat: Add Nit convertion

- book/src/cli-usage.md
- book/src/web-usage.md
- numbat/src/dimension.rs
- numbat/src/lib.rs
- numbat/src/registry.rs
```
>>> info Mass
Dimension:   Mass (Base dimension)
Units:       dalton, firkin, grain, gram, long_hundredweight, long_ton, ounce, planck_mass, pound, stone, tonne
>>> info Energy
Dimension:   Energy = Length² × Mass / Time²
Equivalent:  Torque
Units:       BTU, calorie, electronvolt, erg, joule, planck_energy, Ry, therm, thermie, watthour
```
closes #674
> info <dimension>

- numbat/src/prefix.rs
- numbat/src/prefix_parser.rs
> Add new binary prefixes for Ri and Qi

- book/src/example-numbat_syntax.md
- examples/numbat_syntax.nbt
- numbat/src/parser.rs
- numbat/src/tokenizer.rs
- numbat/tests/interpreter.rs
> 395 add semicolon as optional statement separator
